services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - app_data:/var/www/html
      - nginx_config:/etc/nginx/conf.d
    depends_on:
      - php

#  php:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      network: host
#    container_name: php
#    volumes:
#      - app_data:/var/www/html

  php:
    image: ghcr.io/zainmajeedch/docker-compose-project:latest
    container_name: php
    volumes:
      - app_data:/var/www/html

  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data

  worker:
    image: php:8.3-cli
#    container_name: worker
    working_dir: /var/www/html
    volumes:
      - worker_data:/var/www/html
    command: php worker.php
    depends_on:
      - redis

volumes:
  app_data:
  nginx_config:
  mariadb_data:
  redis_data:
  worker_data:
